# Generated by Django 5.0.1 on 2026-08-20 13:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('SEASONAL_HIGH', 'Seasonal High'), ('SEASONAL_LOW', 'Seasonal Low'), ('UPWARD_TREND', 'Upward Trend'), ('DOWNWARD_TREND', 'Downward Trend'), ('STABLE', 'Stable'), ('VOLATILE', 'Volatile')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the trend')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence in this trend (0-100)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supporting_data', models.JSONField(default=dict, help_text='Additional data supporting this trend')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Trend',
                'verbose_name_plural': 'Price Trends',
                'db_table': 'price_trends',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('SEASONAL', 'Seasonal Pattern'), ('BEST_TIME_TO_BUY', 'Best Time to Buy'), ('PRICE_ALERT', 'Price Alert'), ('SAVINGS_OPPORTUNITY', 'Savings Opportunity'), ('GENERAL', 'General Insight')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_insights', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_insights', to='products.product')),
            ],
            options={
                'verbose_name': 'Market Insight',
                'verbose_name_plural': 'Market Insights',
                'db_table': 'market_insights',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Change from previous period', max_digits=10)),
                ('price_change_percent', models.DecimalField(decimal_places=2, help_text='Percentage change from previous period', max_digits=6)),
                ('price_volatility', models.DecimalField(blank=True, decimal_places=2, help_text='Standard deviation of prices in this period', max_digits=6, null=True)),
                ('data_points_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_analytics', to='products.product')),
            ],
            options={
                'verbose_name': 'Price Analytics',
                'verbose_name_plural': 'Price Analytics',
                'db_table': 'price_analytics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_type', models.CharField(choices=[('WHOLESALE', 'Wholesale Price'), ('RETAIL', 'Retail Price'), ('BASKET', 'Basket Price'), ('DIRECT', 'Direct Purchase Price'), ('MARKET_SURVEY', 'Market Survey Price')], max_length=20)),
                ('effective_date', models.DateField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Quantity at which this price was available', null=True)),
                ('notes', models.TextField(blank=True)),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='baskets.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'db_table': 'price_history',
                'ordering': ['-effective_date', '-recorded_at'],
            },
        ),
    ]
