# Generated by Django 5.0.1 on 2026-08-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='pricetrend',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_trends', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='priceanalytics',
            index=models.Index(fields=['product', 'period_type', 'period_start'], name='price_analy_product_ac6711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='priceanalytics',
            unique_together={('product', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'effective_date'], name='price_histo_product_356839_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'price_type', 'effective_date'], name='price_histo_product_9705a4_idx'),
        ),
    ]
