# Generated by Django 5.0.1 on 2026-08-21 14:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priceanalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='priceanalytics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='pricetrend',
            name='product',
        ),
        migrations.CreateModel(
            name='BiMonthlyMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Calendar year e.g. 2026')),
                ('period', models.CharField(choices=[('Sept - Oct', 'Sept - Oct'), ('Nov - Dec', 'Nov - Dec'), ('Jan - Feb', 'Jan - Feb'), ('Mar - Apr', 'Mar - Apr'), ('May - Jun', 'May - Jun'), ('Jul - Aug', 'Jul - Aug')], max_length=20)),
                ('min_average_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_average_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_weekly_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_weekly_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_weekly_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_weekly_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bi_monthly_data', to='products.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bi_monthly_data', to='products.product')),
            ],
            options={
                'verbose_name': 'Bi-Monthly Market Data',
                'verbose_name_plural': 'Bi-Monthly Market Data',
                'db_table': 'bi_monthly_market_data',
                'ordering': ['year', 'period'],
                'unique_together': {('product', 'brand', 'year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='FinancialLossAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('peak_surge_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discounted_optimal_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('single_company_loss', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('aggregate_500_companies_loss', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_loss_analyses', to='products.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_loss_analysis', to='products.product')),
            ],
            options={
                'verbose_name': 'Financial Loss Analysis',
                'verbose_name_plural': 'Financial Loss Analyses',
                'db_table': 'financial_loss_analysis',
            },
        ),
        migrations.CreateModel(
            name='ProcurementGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_best_season', models.CharField(default='Sept - Oct', max_length=50)),
                ('second_best_season', models.CharField(default='May - Jun', max_length=50)),
                ('third_best_season', models.CharField(default='Jan - Feb', max_length=50)),
                ('seasonal_buying_guide_notes', models.TextField(blank=True, help_text='Detailed guidance text for seasonal procurement')),
                ('recommendation_summary', models.TextField(blank=True, help_text='General recommendation text for procurement officers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_guidances', to='products.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_guidance', to='products.product')),
            ],
            options={
                'verbose_name': 'Procurement Guidance',
                'verbose_name_plural': 'Procurement Guidance',
                'db_table': 'procurement_guidance',
            },
        ),
        migrations.CreateModel(
            name='WeeklySpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True, help_text='Month number 1-12')),
                ('week_number', models.IntegerField(help_text='Week number 1 to 5')),
                ('week_label', models.CharField(help_text='e.g. Aug W1', max_length=20)),
                ('direct_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_spot_prices', to='products.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_spot_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Weekly Spot Price',
                'verbose_name_plural': 'Weekly Spot Prices',
                'db_table': 'weekly_spot_prices',
                'ordering': ['year', 'month', 'week_number'],
                'unique_together': {('product', 'brand', 'year', 'month', 'week_number')},
            },
        ),
        migrations.DeleteModel(
            name='MarketInsight',
        ),
        migrations.DeleteModel(
            name='PriceAnalytics',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='PriceTrend',
        ),
    ]
