# Generated by Django 5.0.1 on 2026-08-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_priceanalytics_unique_together_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiallossanalysis',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_loss_analyses', to='products.product'),
        ),
        migrations.AlterField(
            model_name='procurementguidance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_guidances', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='financiallossanalysis',
            unique_together={('product', 'brand')},
        ),
        migrations.AlterUniqueTogether(
            name='procurementguidance',
            unique_together={('product', 'brand')},
        ),
    ]
