# Generated by Django 5.0.1 on 2026-08-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DELIVERY_STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.delivery'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_number'], name='deliveries_deliver_4cdab8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'scheduled_date'], name='deliveries_status_86c264_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryorder',
            unique_together={('delivery', 'order')},
        ),
    ]
