# Generated by Django 5.0.1 on 2026-08-14 10:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('basket_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SIX_MONTH', 'Six Month')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Orders'), ('CLOSING_SOON', 'Closing Soon'), ('CLOSED', 'Closed'), ('PROCUREMENT', 'In Procurement'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('target_participants', models.IntegerField(default=10, help_text='Target number of participating organizations', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_participants', models.IntegerField(default=0)),
                ('price_tiers', models.JSONField(default=list, help_text='List of price tiers based on quantity/participants')),
                ('total_estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_final_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'db_table': 'baskets',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='BasketParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('has_placed_order', models.BooleanField(default=False)),
                ('total_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_items', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Basket Participant',
                'verbose_name_plural': 'Basket Participants',
                'db_table': 'basket_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_estimated_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_quantity_ordered', models.IntegerField(default=0)),
                ('minimum_basket_quantity', models.IntegerField(default=1, help_text='Minimum total quantity for this product in the basket', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Basket Product',
                'verbose_name_plural': 'Basket Products',
                'db_table': 'basket_products',
                'ordering': ['product__name'],
            },
        ),
    ]
