# Generated by Django 5.0.1 on 2026-08-20 13:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_quantity', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Basket Participant',
                'verbose_name_plural': 'Basket Participants',
                'db_table': 'basket_participants',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SIX_MONTH', 'Six Month')], default='WEEKLY', max_length=20)),
                ('merkato_retailer_price', models.DecimalField(decimal_places=2, help_text='Auto-filled from brand catalog', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('regular_market_price', models.DecimalField(decimal_places=2, help_text='Auto-filled from brand catalog', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_quantity', models.PositiveIntegerField(default=100, help_text='Target commitment quantity to trigger fulfillment', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_quantity', models.PositiveIntegerField(default=0, help_text='Total committed quantity by all participants')),
                ('babi_platform_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price given to participants after fulfillment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale cost from supplier', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baskets', to='products.brand')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'db_table': 'baskets',
                'ordering': ['-created_at'],
            },
        ),
    ]
