# Generated by Django 5.0.1 on 2026-08-14 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_baskets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basketparticipant',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='baskets.basket'),
        ),
        migrations.AddField(
            model_name='basketparticipant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_participations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='baskets.basket'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basket_products', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['status', 'closes_at'], name='baskets_status_9a83b2_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['basket_type', 'status'], name='baskets_basket__77f73c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='basketparticipant',
            unique_together={('basket', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='basketproduct',
            unique_together={('basket', 'product')},
        ),
    ]
