# Generated by Django 5.0.1 on 2026-08-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_baskets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baskets', to='products.product'),
        ),
        migrations.AddField(
            model_name='basketparticipant',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='baskets.basket'),
        ),
        migrations.AddField(
            model_name='basketparticipant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_participations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='basketparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['status'], name='baskets_status_035536_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['duration_type', 'status'], name='baskets_duratio_ae9d6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='basketparticipant',
            unique_together={('basket', 'user')},
        ),
    ]
