# Generated by Django 5.0.1 on 2026-08-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='carrier_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='basket',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='delivery_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='basket',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending Logistics'), ('SCHEDULED', 'Scheduled for Dispatch'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='basket',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
