# Generated by Django 5.0.1 on 2026-08-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_basket_carrier_name_basket_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_full_notification_sent',
            field=models.BooleanField(default=False, help_text='Flag to prevent duplicate 100% full notifications for this basket'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
