# Generated by Django 5.0.1 on 2026-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(blank=True, max_length=100)),
                ('woreda', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('contact_person_phone', models.CharField(max_length=20)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
                'db_table': 'delivery_addresses',
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('organization_type', models.CharField(choices=[('School', 'School'), ('University', 'University'), ('Government Office', 'Government Office'), ('NGO', 'NGO'), ('Private Company', 'Private Company'), ('Bank & Financial Institution', 'Bank & Financial Institution'), ('Hospital & Health Centre', 'Hospital & Health Centre')], max_length=50)),
                ('tin_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('address_type', models.CharField(choices=[('autocomplete', 'Autocomplete'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('address_formatted', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('region', models.CharField(default='Addis Ababa City Administration', max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procurement Contact',
                'verbose_name_plural': 'Procurement Contacts',
                'db_table': 'procurement_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
